<!doctype html>

<html lang="en">
<head>
  <meta charset="utf-8">

  <title>Retro Guestbook</title>
  <link rel="stylesheet" href="http://yui.yahooapis.com/pure/0.6.0/pure-min.css">
</head>

<body>
<div class="pure-menu pure-menu-horizontal">
    <ul class="pure-menu-list">
        <li class="pure-menu-item"><a href="/" class="pure-menu-link">Guestbook</a></li>
        <li class="pure-menu-item"><a href="/webhooks" class="pure-menu-link">Webhooks</a></li>
    </ul>
</div>

