<?php
include "header.phtml";
?>
<h1>Add Comment</h1>

<form class="pure-form pure-form-aligned" method="post">
    <fieldset>
        <div class="pure-control-group">
            <label for="comment">Remarks</label>
            <textarea name="comment" id="comment" placeholder="Enter something here..." rows="10" cols="65"></textarea>

        </div>

        <div class="pure-control-group">
            <label for="name">Name</label>
            <input name="name" id="name" type="text" placeholder="Jane Doe" size="32">
        </div>

        <div class="pure-controls">
            <input type="submit" class="pure-button pure-button-primary">
        </div>
    </fieldset>
</form>
<?php
include "footer.phtml";
?>

